apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["nsenter", "--mount=/proc/1/ns/mnt", "--", "/bin/bash"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
  hostPID: true
  hostNetwork: true
