apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["nsenter", "--pid=/proc/1/ns/pid", "--", "/bin/bash"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
  hostPID: true
  hostNetwork: true
